"use client"

import { BrainCircuit, Crosshair, Target, Workflow } from "lucide-react"
import { motion } from "framer-motion"

import type { CoachContext } from "@/features/coach/types/coach"

export function ContextPanel({ context }: { context: CoachContext | null }) {
  const skills = context?.skills ?? []
  const progress = Math.round(context?.roadmapProgress ?? 0)
  return <motion.aside initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.15 }} className="overflow-hidden rounded-3xl border border-white/[0.08] bg-[#18181B]/70 xl:sticky xl:top-24 xl:self-start"><header className="border-b border-white/[0.07] p-5"><div className="flex items-center gap-2 text-sm font-semibold text-white"><BrainCircuit className="size-4 text-[#A78BFA]" />Career Profile</div><p className="mt-1 text-xs text-[#71717A]">Context used for this conversation</p></header><div className="space-y-6 p-5"><ContextRow icon={Target} label="Target" value={context?.targetRole ?? "Loading profile..."} /><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#71717A]">Skills</p><div className="flex flex-wrap gap-2">{skills.length ? skills.map((skill) => <span key={skill} className="rounded-lg border border-white/[0.08] bg-white/[0.035] px-2.5 py-1.5 text-xs text-[#D4D4D8]">{skill}</span>) : <span className="text-xs text-[#71717A]">Skill context is being prepared.</span>}</div></div><div><div className="flex items-end justify-between"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#71717A]"><Workflow className="size-3.5 text-[#10B981]" />Roadmap progress</div><span className="text-lg font-semibold text-white">{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[0.07]"><motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }} transition={{ duration: 0.9, delay: 0.2 }} className="h-full rounded-full bg-gradient-to-r from-[#8B5CF6] to-[#10B981]" /></div></div><ContextRow icon={Crosshair} label="Current focus" value={context?.currentFocus ?? "Preparing focus..."} /></div><footer className="border-t border-white/[0.07] bg-[#111113]/60 p-5 text-xs leading-5 text-[#71717A]">Your coach uses this profile context to keep guidance relevant to your goal.</footer></motion.aside>
}

function ContextRow({ icon: Icon, label, value }: { icon: typeof Target; label: string; value: string }) { return <div className="flex items-start gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#A78BFA]"><Icon className="size-3.5" /></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#71717A]">{label}</p><p className="mt-1 text-sm font-medium leading-5 text-white">{value}</p></div></div> }
