"use client"

import { motion } from "framer-motion"
import { CalendarRange, Flag, Route, Target } from "lucide-react"

import { CurrentFocusCard } from "@/components/roadmap/current-focus-card"
import { MilestoneCard } from "@/components/roadmap/milestone-card"
import { ProgressIndicator } from "@/components/roadmap/progress-indicator"
import { ResourceCard } from "@/components/roadmap/resource-card"
import { RoadmapTimeline } from "@/components/roadmap/roadmap-timeline"
import { learningResources, projectMilestones, roadmapStages } from "@/features/roadmap/data/mock-roadmap"

export default function RoadmapPage() {
  return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="mx-auto max-w-[90rem] space-y-8 sm:space-y-10"><header className="border-b border-white/[0.07] pb-7"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#8B5CF6]"><Route className="size-4" />Adaptive career planning</div><h1 className="text-3xl font-semibold tracking-[-0.045em] text-white sm:text-4xl">Your AI Career Roadmap</h1><p className="mt-3 text-sm text-[#A1A1AA] sm:text-base">A personalized path from your current skills to your target role.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><HeaderMetric icon={Target} label="Target role" value="AI Engineer" /><HeaderMetric icon={CalendarRange} label="Estimated journey" value="6 Months" /><HeaderMetric icon={Flag} label="Current stage" value="Stage 2 of 5" className="col-span-2 sm:col-span-1" /></div></div><div className="mt-6 max-w-xl"><ProgressIndicator value={32} /></div></header><section className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(22rem,0.75fr)]"><div><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#10B981]">Career journey</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em] text-white">Five stages to career ready</h2><p className="mt-2 text-sm text-[#71717A]">Open each stage to inspect the capabilities in your path.</p></div><RoadmapTimeline stages={roadmapStages} /></div><div className="xl:sticky xl:top-24 xl:self-start"><CurrentFocusCard /></div></section><section><SectionHeading eyebrow="Proof of skill" title="Project Milestones" description="Build evidence as you progress—not just course completion." /><div className="grid gap-4 lg:grid-cols-3">{projectMilestones.map((milestone, index) => <MilestoneCard key={milestone.title} milestone={milestone} index={index} />)}</div></section><section><SectionHeading eyebrow="Curated for this stage" title="Learning Resources" description="A focused resource mix for Backend Engineering." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{learningResources.map((resource, index) => <ResourceCard key={resource.type} resource={resource} index={index} />)}</div></section></motion.div>
}

function HeaderMetric({ icon: Icon, label, value, className = "" }: { icon: typeof Target; label: string; value: string; className?: string }) { return <div className={`rounded-2xl border border-white/[0.08] bg-[#18181B] px-4 py-3 ${className}`}><div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.14em] text-[#71717A]"><Icon className="size-3.5 text-[#A78BFA]" />{label}</div><p className="mt-2 whitespace-nowrap text-sm font-medium text-white">{value}</p></div> }
function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#F59E0B]">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em] text-white">{title}</h2><p className="mt-2 text-sm text-[#71717A]">{description}</p></div> }
