"""add skill model

Revision ID: 37ecc23f37e6
Revises: 5d49179d5d0e
Create Date: 2026-08-08 22:29:13.287787
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37ecc23f37e6'
down_revision: Union[str, Sequence[str], None] = '5d49179d5d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
