"""add career goal model

Revision ID: 5d49179d5d0e
Revises: b692f2efe3da
Create Date: 2026-08-08 22:27:09.905602
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d49179d5d0e'
down_revision: Union[str, Sequence[str], None] = 'b692f2efe3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
