"""add user profile model

Revision ID: b692f2efe3da
Revises: 20260808_0001
Create Date: 2026-08-08 22:24:55.311956
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b692f2efe3da'
down_revision: Union[str, Sequence[str], None] = '20260808_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
