"""add roadmap models

Revision ID: d938b989e579
Revises: 352b4084e427
Create Date: 2026-08-08 22:49:08.909633
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd938b989e579'
down_revision: Union[str, Sequence[str], None] = '352b4084e427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['career_goal_id'], ['career_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_steps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
